my-bigquery-db:
  target: dev # this is the default target
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: dbt-learn-400519
      dataset: dbt_learn
      keyfile: keys/dbt-learn-gcp.json
      threads: 2
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: dbt-prod-ad
      dataset: dbt_prod
      keyfile: "{{ env_var('DBT_GCP_JSON_KEY_FILE_LOCATION') }}"
      threads: 2