name: dbt CI/CD
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
  workflow_dispatch:

env:
  DBT_PROJECT_DIR: ./
  DBT_PROFILES_DIR: ./
  DBT_GCP_JSON_KEY_FILE_LOCATION: /tmp/sa_key_file.json
  DBT_GCP_JSON_KEY_FILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}

jobs:
  dbt_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Create and start virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  

      - name: Write GCP service account key
        env:
          DBT_KEYFILE: ${{ secrets.DBT_GCP_JSON_KEY_FILE }}
        run: |
          echo "$DBT_KEYFILE" > /tmp/sa_key_file.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.DBT_GCP_JSON_KEY_FILE }} # Use the GitHub secret you created
      
      - name: Install dbt dependencies
        run: dbt deps

      - name: dbt run
        run: dbt run --full-refresh --target prod

      - name: Run dbt test
        run: dbt test --target prod
        
      - name: Upload manifest.json to GCS
        uses: google-github-actions/upload-cloud-storage@v2
        with:
          path: target/manifest.json
          destination: my-dbt-artifacts-ad # Replace with your bucket name and optional prefix
          parent: false # Optional: Prevents the "target/" directory from being included in the GCS path